# Generated by Django 3.0.6 on 2021-02-15 06:10

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('clinical_data', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.default_appointment_clinical_data)),
                ('status', models.CharField(default='scheduled', max_length=100)),
                ('start', models.DateTimeField()),
                ('actual_start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('actual_end', models.DateTimeField()),
                ('scheduled_on', models.DateTimeField(auto_now_add=True)),
                ('scheduling_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.create_default_form)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_icd_code', models.CharField(blank=True, max_length=200)),
                ('diagnosis_description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('diagnosed_on', models.DateField(blank=True, null=True)),
                ('diagnosed_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_by', models.CharField(blank=True, max_length=300)),
                ('requires_authorization', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=400)),
                ('reason_stopped', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('medication', 'Medication Refill'), ('insurance_authorization_medication', 'Medication Insurance Authorization'), ('other', 'Other'), ('clinical_question', 'Clinical Question')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], max_length=50)),
                ('request_description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('news', models.TextField(blank=True)),
                ('display', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address_one', models.CharField(max_length=500)),
                ('address_two', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=12)),
                ('npi', models.CharField(max_length=100)),
                ('first_appointment_starts', models.TimeField()),
                ('last_appointment_ends', models.TimeField()),
                ('close', models.TimeField()),
                ('tax_id', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr', 'Dr'), ('Nurse', 'Nurse')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('npi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_surgeries', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequestUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_request_updates', to='api.PatientRequest')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('other_provider_notes', 'Clinical notes from other provider'), ('lab_reports', 'Lab Reports'), ('radiology_report', 'Radiology Report')], max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('received_on', models.DateField()),
                ('provider_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRadiology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=200)),
                ('findings', models.TextField(blank=True)),
                ('diagnosis', models.ManyToManyField(blank=True, related_name='radiology_history', to='api.PatientDiagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicationPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('refills', models.SmallIntegerField(blank=True, null=True)),
                ('written_on', models.DateField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='api.PatientMedication')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_written_by', to='api.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('new_strength', models.CharField(blank=True, max_length=100)),
                ('new_frequency', models.CharField(blank=True, max_length=100)),
                ('prescription_type', models.CharField(blank=True, max_length=100)),
                ('refills_given', models.SmallIntegerField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication_history', to='api.PatientMedication')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicationChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_strength', models.CharField(blank=True, max_length=200)),
                ('new_frequency', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('reason_for_change', models.TextField(blank=True)),
                ('date_changed', models.DateField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication_changes', to='api.PatientMedication')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicationAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField()),
                ('authorization_number', models.CharField(blank=True, max_length=500)),
                ('contact_method', models.TextField(blank=True)),
                ('authorized_on', models.DateField(blank=True, null=True)),
                ('date_of_next_authorization', models.DateField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_authorizations', to='api.PatientMedication')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to='api.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='diagnosis_medications', to='api.PatientMedication'),
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnoses', to='api.Patient'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(blank=True, max_length=200)),
                ('tradingPartnerId', models.CharField(blank=True, max_length=200)),
                ('primary', models.BooleanField(blank=True, null=True)),
                ('group_ID', models.CharField(blank=True, max_length=200)),
                ('bin_number', models.CharField(blank=True, max_length=200)),
                ('pcn', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary')], max_length=50)),
                ('member_id', models.CharField(blank=True, max_length=30)),
                ('relationship_code', models.CharField(blank=True, max_length=2)),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('date_terminated', models.DateField(blank=True, null=True)),
                ('copay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_insurances', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_patient', models.CharField(blank=True, choices=[('self', 'Self'), ('parent', 'Parent'), ('spouse', 'Spouse')], max_length=20, null=True)),
                ('guarantor_first_name', models.CharField(blank=True, max_length=30)),
                ('guarantor_last_name', models.CharField(blank=True, max_length=30)),
                ('guarantor_middle_name', models.CharField(blank=True, max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_guarantors', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(default='not_listed', max_length=50)),
                ('gender', models.CharField(default='not_listed', max_length=50)),
                ('marital_status', models.CharField(default='not_listed', max_length=50)),
                ('employment_status', models.CharField(default='not_listed', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_demographics', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('special_instructions', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_contact_methods', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.Appointment')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Guarantor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('form_type', models.CharField(max_length=100)),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.create_default_appointment_form)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_forms', to='api.Appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.Provider'),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_allergies', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(default='not_listed', max_length=150)),
                ('address_two', models.CharField(default='not_listed', max_length=50)),
                ('city', models.CharField(default='not_listed', max_length=50)),
                ('state', models.CharField(default='not_listed', max_length=50)),
                ('zip_code', models.CharField(default='not_listed', max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_address', to='api.Patient')),
            ],
        ),
    ]
