# Generated by Django 3.0.6 on 2022-02-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
