# Generated by Django 3.0.6 on 2022-08-03 09:45

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.default_appointment_details),
        ),
    ]
