# Generated by Django 3.0.6 on 2022-02-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220223_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='status',
        ),
    ]
