# Generated by Django 3.0.6 on 2022-11-28 15:57

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220826_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.default_form_details, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.default_form_details, null=True),
        ),
    ]
