# Generated by Django 3.0.6 on 2022-07-02 08:07

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220312_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='physical_exam_form',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.default_physical_exam_form),
        ),
        migrations.AddField(
            model_name='settings',
            name='review_of_systems_form',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.default_review_of_systems_form),
        ),
    ]
