# Generated by Django 3.0.6 on 2023-02-22 05:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221128_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
    ]
