# Generated by Django 3.0.6 on 2023-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='active',
        ),
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.RemoveField(
            model_name='form',
            name='details',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form',
        ),
        migrations.RemoveField(
            model_name='form',
            name='location',
        ),
        migrations.RemoveField(
            model_name='form',
            name='properties',
        ),
        migrations.AddField(
            model_name='form',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
