# Generated by Django 3.0.6 on 2023-03-01 00:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230222_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='details',
        ),
        migrations.RemoveField(
            model_name='request',
            name='details',
        ),
        migrations.AddField(
            model_name='insurance',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='request',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
    ]
