# Generated by Django 3.0.6 on 2023-03-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230301_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='fields',
            new_name='updates',
        ),
    ]
