# Generated by Django 3.0.6 on 2023-03-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230308_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name_plural': 'Forms'},
        ),
    ]
