# Generated by Django 3.0.6 on 2023-03-15 05:19

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230308_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assessments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='complaints',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='physical_exam',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plans',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review_of_systems',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
