# Generated by Django 3.0.6 on 2023-03-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230321_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='details',
        ),
    ]
