# Generated by Django 3.0.6 on 2023-09-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_appointment_aitext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialAIAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
