# Generated by Django 3.0.6 on 2023-09-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_artificialaiappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='aitext',
        ),
        migrations.AddField(
            model_name='appointment',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
