# Generated by Django 3.0.6 on 2023-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230930_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ainote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
