# Generated by Django 3.0.6 on 2024-03-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20231207_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='claim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cleaneduptranscript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
